// Generates src/abi.ts from the Foundry build output and src/deployments.json from
// ../deployments/*.json. Both generated files are committed so the frontend builds on Vercel
// without Foundry installed.
//
//   forge build && npm run sync
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "../..");
const src = path.resolve(import.meta.dirname, "../src");

const contracts = {
  vaultAbi: "OptionsVault",
  engineAbi: "PricingEngine",
  resolverAbi: "SettlementResolver",
  optionTokenAbi: "OptionToken",
  usdcAbi: "TestUSDC",
};

let abiTs = "// GENERATED by scripts/sync.mjs from forge build output. Do not edit.\n";
for (const [exportName, contract] of Object.entries(contracts)) {
  const file = path.join(root, "out", `${contract}.sol`, `${contract}.json`);
  const abi = JSON.parse(fs.readFileSync(file, "utf8")).abi;
  abiTs += `\nexport const ${exportName} = ${JSON.stringify(abi)} as const;\n`;
}
fs.writeFileSync(path.join(src, "abi.ts"), abiTs);

// Real deployments go in the committed file; the local anvil one (chain 31337) goes in a
// gitignored file so its throwaway addresses can never ship to production.
const LOCAL_CHAIN = "31337";
const deployments = {};
const local = {};
const dir = path.join(root, "deployments");
if (fs.existsSync(dir)) {
  for (const f of fs.readdirSync(dir)) {
    if (!f.endsWith(".json")) continue;
    const json = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    (String(json.chainId) === LOCAL_CHAIN ? local : deployments)[String(json.chainId)] = json;
  }
}
fs.writeFileSync(path.join(src, "deployments.json"), JSON.stringify(deployments, null, 2) + "\n");
fs.writeFileSync(path.join(src, "deployments.local.json"), JSON.stringify(local, null, 2) + "\n");

console.log(
  `abi.ts: ${Object.keys(contracts).length} ABIs; deployments: ${Object.keys(deployments).join(", ") || "none"}; local: ${Object.keys(local).join(", ") || "none"}`,
);
